title: Forgotten Women in STEAM
author: Morgan Carroll
subtitle: A tribute to the forgotten women of STEAM

url: "https://themorgan.io"
baseurl: "/forgottenwomen-steam"

footer_only_homepage: true
footer_url: "https://themorgan.io"
footer_text: "Created by Morgan Carroll"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
